name: Test Secrets

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show Username Exists
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "Username is EMPTY"
            exit 1
          else
            echo "Username exists"
          fi